### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by ArenM**
**Todo**:
 - [x] fix opengl rendering to an image on windows
 - [x] make sure the "fancy" gate drag and drop method is used on windows
 - [x] load the config file from user-writeable path when installed, related to #58
 - [x] install the `res` directory to the correct location
 - [x] buld & run on windows to test for regressions
 - [x] test building in a clean system (docker container) to write more complete build instructions

### CODE REVIEW

**Comment by ArenM** [comment]
I have two methods for getting dragging gates from the sidebar working, but both seem to have drawbacks. @JoeHCQ1 do you have an opinion which would be better?

9fdcbe1 uses the wxWidgets drag and drop class which should be better supported cross platform, but it doesn't allow showing the gate before it has been placed on the canvas.

d2686eb calls the `klsGLCanvas::beginDrag` from the `gateImage` when a drag starts, which forwards the events, but seems more likely to cause unintended side-effects on different platforms.

**Comment by JoeHCQ1** [comment]
> but seems more likely to cause unintended side-effects on different platforms.

You said "likely". Have you been able to see this problem show up yet? If not, @ArenM I'd leave a comment noting the wxWidgets drag and drop alternative and even a reference to the commit sha (which will exist for forever as long as we don't squash-merge this PR) and use the klsGLCanvas option. A preview I think is an important user-aid.

**Comment by ArenM** [comment]
Make sense. I just pushed a cleaned up version of the drag and drop by capturing the mouse. I left the wx drag and drop code in place, and added an ifdef so it doesn't get run.

**Comment by HRahikainen** [comment]
@ArenM Do you think there is still a lot to do to get this PR ready? Seemed to work nicely for me. Would be nice to get it merged to dev to continue to iterate on top of it :)

**Comment by ArenM** [comment]
Yes this is ready for review

If it helps get things moving I could try to split off some more bite-sized chunks from this (some of these changes are pretty interdependent though). I could also read through my changes again, since I haven't looked at this in a couple weeks it might be able to serve as a first round of review.

If I do either of those, I'll probably end up rebaseing large parts of this so I want to make sure no one is trying to review it first.

**Comment by JoeHCQ1** [comment]
@ArenM you don't need to break it into smaller pieces. If you're ready and it sounds like you are, I'll review and verify the changes from my end.

**Comment by JoeHCQ1** [comment]
So I am getting a few problems so far, I'll see how many I can fix.

1. I can't install a late enough version of wxwidgets from my ubuntu repo (20.04). I am working around that via the flag `-DUSE_SYSTEM_WXWIDGETS=0`.
2. I get a series of compile errors. In one case, I needed to add an include for `std::vector`. I'm working on the rest at the moment.

**Comment by JoeHCQ1** [comment]
I merged this with a few more fixes, see the commit history on dev-v2.4 for reference:

image

Note the commit message saying "Added  to fix..." was meant to say "Added `#include <vector>` to fix..." but yay old backtick notation in bash, it interpolated that as a function.

**Pull request merged**
