### PR TITLE
Cmake clean up update

### PR DESCRIPTION
**Pull request by JoeHCQ1**
- Changed some CMake lines to use functions that CMake recommends (may well have been added to CMake since the CMakeLists.txt was written).
  - Visual Studio is now aware of your Headers and Source files as separate groups where they had all been considered source files. It compiled that way, but this provides Visual Studio with more meta-information.
  - Updated the way we're specifying project version.
  - Updated the way we specify the C++ standard (did not change the standard).
- Organized the .cpp and .h files into their own directories.
- Updated an "all-rights-reserved" copyright notice to reference GPLv3.0 in accordance with the LICENSE in this repo.
- I have tested that this still builds and the installer at least starts running. Since I didn't change any program logic I didn't see a need to test the application further. With a better understanding of our CMake setup though, and some discoveries through work, I would like to get some unit testing built-in so I can _know_ much of the program still works instead of just suspecting it does.

@kshomper let me know if you have any feedback -

Stuff I've added since:

- Made logic into a statically linked library and added the [Catch2 test framework via their cmake integration](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#top). I have a hello-world type test working. I intend to get fairly heavy logic testing in place.

### CODE REVIEW

**Comment by JoeHCQ1** [comment]
Actually, let's wait on the merge. I'm figuring out how to do more of what I was looking to do thanks to the [CppCheck CMakeLists.txt](https://github.com/danmar/cppcheck/blob/main/gui/CMakeLists.txt) is set up. I'd mark the PR as a draft but that might be a GitLab only feature.

**Comment by JoeHCQ1** [comment]
@kshomper are you comfortable with these changes? Once merged I can start on unit tests. I could start on those now, but I anticipate that as I test the code I'll modify it and I don't want to bloat this PR. 

To test, you'll want to regenerate the solution file with CMake. Here are the settings I have. The Catch2 related ones won't show up until you've generated or at least configured because it's pulled in (see logic/CMakeLists.txt).
image

**Comment by kshomper** [comment]
Joe ... Everything looks fine. Thanks for cleaning up the build process. Keith

**Review by kshomper — APPROVED** [review]
Looks fine. Thank you.

**Pull request merged**
